apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: verigrade
  labels:
    app: verigrade
    component: secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
            namespace: verigrade
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key
            namespace: verigrade
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: verigrade-secrets
  namespace: verigrade
  labels:
    app: verigrade
    component: secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: verigrade-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: verigrade
          component: secrets
      data:
        DATABASE_URL: "{{ .database_url }}"
        REDIS_URL: "{{ .redis_url }}"
        JWT_SECRET: "{{ .jwt_secret }}"
        JWT_REFRESH_SECRET: "{{ .jwt_refresh_secret }}"
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        STRIPE_SECRET_KEY: "{{ .stripe_secret_key }}"
        STRIPE_PUBLISHABLE_KEY: "{{ .stripe_publishable_key }}"
        PLAID_CLIENT_ID: "{{ .plaid_client_id }}"
        PLAID_SECRET: "{{ .plaid_secret }}"
        SENTRY_DSN: "{{ .sentry_dsn }}"
        NEW_RELIC_LICENSE_KEY: "{{ .new_relic_license_key }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        API_KEY_SECRET: "{{ .api_key_secret }}"
        GOOGLE_CLIENT_ID: "{{ .google_client_id }}"
        GOOGLE_CLIENT_SECRET: "{{ .google_client_secret }}"
        MICROSOFT_CLIENT_ID: "{{ .microsoft_client_id }}"
        MICROSOFT_CLIENT_SECRET: "{{ .microsoft_client_secret }}"
        WEBHOOK_SECRET: "{{ .webhook_secret }}"
        BACKUP_ENCRYPTION_KEY: "{{ .backup_encryption_key }}"
  data:
  - secretKey: database_url
    remoteRef:
      key: verigrade/production/secrets
      property: DATABASE_URL
  - secretKey: redis_url
    remoteRef:
      key: verigrade/production/secrets
      property: REDIS_URL
  - secretKey: jwt_secret
    remoteRef:
      key: verigrade/production/secrets
      property: JWT_SECRET
  - secretKey: jwt_refresh_secret
    remoteRef:
      key: verigrade/production/secrets
      property: JWT_REFRESH_SECRET
  - secretKey: aws_access_key_id
    remoteRef:
      key: verigrade/production/secrets
      property: AWS_ACCESS_KEY_ID
  - secretKey: aws_secret_access_key
    remoteRef:
      key: verigrade/production/secrets
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: stripe_secret_key
    remoteRef:
      key: verigrade/production/secrets
      property: STRIPE_SECRET_KEY
  - secretKey: stripe_publishable_key
    remoteRef:
      key: verigrade/production/secrets
      property: STRIPE_PUBLISHABLE_KEY
  - secretKey: plaid_client_id
    remoteRef:
      key: verigrade/production/secrets
      property: PLAID_CLIENT_ID
  - secretKey: plaid_secret
    remoteRef:
      key: verigrade/production/secrets
      property: PLAID_SECRET
  - secretKey: sentry_dsn
    remoteRef:
      key: verigrade/production/secrets
      property: SENTRY_DSN
  - secretKey: new_relic_license_key
    remoteRef:
      key: verigrade/production/secrets
      property: NEW_RELIC_LICENSE_KEY
  - secretKey: encryption_key
    remoteRef:
      key: verigrade/production/secrets
      property: ENCRYPTION_KEY
  - secretKey: api_key_secret
    remoteRef:
      key: verigrade/production/secrets
      property: API_KEY_SECRET
  - secretKey: google_client_id
    remoteRef:
      key: verigrade/production/secrets
      property: GOOGLE_CLIENT_ID
  - secretKey: google_client_secret
    remoteRef:
      key: verigrade/production/secrets
      property: GOOGLE_CLIENT_SECRET
  - secretKey: microsoft_client_id
    remoteRef:
      key: verigrade/production/secrets
      property: MICROSOFT_CLIENT_ID
  - secretKey: microsoft_client_secret
    remoteRef:
      key: verigrade/production/secrets
      property: MICROSOFT_CLIENT_SECRET
  - secretKey: webhook_secret
    remoteRef:
      key: verigrade/production/secrets
      property: WEBHOOK_SECRET
  - secretKey: backup_encryption_key
    remoteRef:
      key: verigrade/production/secrets
      property: BACKUP_ENCRYPTION_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: verigrade
  labels:
    app: verigrade
    component: secrets
type: Opaque
data:
  access-key-id: QUtJQUlPU0ZPRE5IVEVSTkZOTERBUw==  # Base64 encoded AWS access key
  secret-access-key: d0phbHJYVXRuRkV3R2lLN01Vbmp1M1B5Q1FzN2pYd2J2T0VrZk9iVw==  # Base64 encoded AWS secret key









