[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm install --production"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "node server.js"