apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: verigrade
  labels:
    app: jaeger
    component: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        component: tracing
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.45
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 14268
          name: http
        - containerPort: 14250
          name: grpc
        - containerPort: 5778
          name: config
        - containerPort: 6831
          name: udp
        - containerPort: 6832
          name: udp
        - containerPort: 5775
          name: config
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch-master:9200"
        - name: ES_INDEX_PREFIX
          value: "jaeger"
        - name: ES_TAGS_AS_FIELDS_ALL
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: verigrade
  labels:
    app: jaeger
    component: tracing
spec:
  type: ClusterIP
  ports:
  - port: 16686
    targetPort: 16686
    protocol: TCP
    name: ui
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: http
  - port: 14250
    targetPort: 14250
    protocol: TCP
    name: grpc
  - port: 5778
    targetPort: 5778
    protocol: TCP
    name: config
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: udp
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: udp
  - port: 5775
    targetPort: 5775
    protocol: UDP
    name: config
  selector:
    app: jaeger
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: verigrade
  labels:
    app: jaeger
    component: tracing
data:
  jaeger.yaml: |
    service:
      name: jaeger
      version: 1.45.0
    collector:
      otlp:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    storage:
      type: elasticsearch
      elasticsearch:
        server-urls: http://elasticsearch-master:9200
        index-prefix: jaeger
        tags-as-fields:
          all: true
    query:
      base-path: /jaeger
    agent:
      http-server:
        host-port: 0.0.0.0:5778
      grpc:
        host-port: 0.0.0.0:14250
      thrift-compact:
        host-port: 0.0.0.0:6831
      thrift-binary:
        host-port: 0.0.0.0:6832
      thrift-http:
        host-port: 0.0.0.0:14268









