[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'No build step needed for backend'"]

[start]
cmd = "node index.js"

