global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@verigrade.com'
  smtp_auth_username: 'alerts@verigrade.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each condition enters the routing tree.
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    group_interval: 5s
    repeat_interval: 5m
  - match:
      severity: warning
    receiver: 'warning-alerts'
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
  - match:
      service: 'verigrade-backend'
    receiver: 'backend-alerts'
  - match:
      service: 'verigrade-frontend'
    receiver: 'frontend-alerts'
  - match:
      service: 'postgres'
    receiver: 'database-alerts'
  - match:
      service: 'redis'
    receiver: 'cache-alerts'

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  - source_match:
      alertname: 'InstanceDown'
    target_match:
      alertname: 'HighErrorRate'
    equal: ['instance']

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  pagerduty_configs:
  - service_key: 'your-pagerduty-service-key'
    description: '{{ .GroupLabels.alertname }} - {{ .GroupLabels.cluster }}'
    details:
      summary: '{{ .GroupLabels.alertname }}'
      description: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
      severity: '{{ .GroupLabels.severity }}'
      cluster: '{{ .GroupLabels.cluster }}'
      service: '{{ .GroupLabels.service }}'
  email_configs:
  - to: 'oncall@verigrade.com'
    subject: 'CRITICAL: {{ .GroupLabels.alertname }} - {{ .GroupLabels.cluster }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Cluster: {{ .Labels.cluster }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Started: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts-critical'
    title: 'CRITICAL Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Cluster:* {{ .Labels.cluster }}
      *Service:* {{ .Labels.service }}
      *Instance:* {{ .Labels.instance }}
      *Started:* {{ .StartsAt }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'devops@verigrade.com'
    subject: 'WARNING: {{ .GroupLabels.alertname }} - {{ .GroupLabels.cluster }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Cluster: {{ .Labels.cluster }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Started: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts-warning'
    title: 'WARNING Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Cluster:* {{ .Labels.cluster }}
      *Service:* {{ .Labels.service }}
      *Instance:* {{ .Labels.instance }}
      *Started:* {{ .StartsAt }}
      {{ end }}

- name: 'backend-alerts'
  email_configs:
  - to: 'backend-team@verigrade.com'
    subject: 'Backend Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Started: {{ .StartsAt }}
      {{ end }}

- name: 'frontend-alerts'
  email_configs:
  - to: 'frontend-team@verigrade.com'
    subject: 'Frontend Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Started: {{ .StartsAt }}
      {{ end }}

- name: 'database-alerts'
  email_configs:
  - to: 'dba@verigrade.com'
    subject: 'Database Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Started: {{ .StartsAt }}
      {{ end }}
  pagerduty_configs:
  - service_key: 'your-database-pagerduty-key'
    description: 'Database Alert: {{ .GroupLabels.alertname }}'

- name: 'cache-alerts'
  email_configs:
  - to: 'devops@verigrade.com'
    subject: 'Cache Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Instance: {{ .Labels.instance }}
      Started: {{ .StartsAt }}
      {{ end }}

# Alertmanager configuration for Kubernetes
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: verigrade
  labels:
    app: alertmanager
    component: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alerts@verigrade.com'
      smtp_auth_username: 'alerts@verigrade.com'
      smtp_auth_password: 'your-app-password'
      smtp_require_tls: true

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
        group_wait: 5s
        group_interval: 5s
        repeat_interval: 5m
      - match:
          severity: warning
        receiver: 'warning-alerts'
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'cluster', 'service']

    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://127.0.0.1:5001/'

    - name: 'critical-alerts'
      pagerduty_configs:
      - service_key: 'your-pagerduty-service-key'
        description: '{{ .GroupLabels.alertname }} - {{ .GroupLabels.cluster }}'
      email_configs:
      - to: 'oncall@verigrade.com'
        subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
        body: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

    - name: 'warning-alerts'
      email_configs:
      - to: 'devops@verigrade.com'
        subject: 'WARNING: {{ .GroupLabels.alertname }}'
        body: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'





