'use client';

import { 
  ScaleIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  ShieldCheckIcon,
  UserIcon
} from '@heroicons/react/24/outline';

export default function TermsPage() {
  const sections = [
    {
      title: "Acceptance of Terms",
      icon: CheckCircleIcon,
      content: [
        {
          subtitle: "Agreement to Terms",
          text: "By accessing and using VeriGrade's services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using our services."
        },
        {
          subtitle: "Updates to Terms",
          text: "We reserve the right to update these Terms of Service at any time. We will notify users of any material changes through our platform or via email. Continued use of our services after such changes constitutes acceptance of the new terms."
        },
        {
          subtitle: "Eligibility",
          text: "You must be at least 18 years old and have the legal capacity to enter into this agreement. By using our services, you represent and warrant that you meet these eligibility requirements."
        }
      ]
    },
    {
      title: "Service Description",
      icon: DocumentTextIcon,
      content: [
        {
          subtitle: "AI-Powered Bookkeeping",
          text: "VeriGrade provides AI-powered bookkeeping services, including automated transaction categorization, receipt processing, financial reporting, and related business intelligence tools."
        },
        {
          subtitle: "Service Availability",
          text: "We strive to maintain high service availability but do not guarantee uninterrupted access. We reserve the right to modify, suspend, or discontinue any part of our services with reasonable notice."
        },
        {
          subtitle: "Data Processing",
          text: "Our AI systems process your financial data to provide bookkeeping services. You retain ownership of your data while granting us necessary rights to process and analyze it for service provision."
        }
      ]
    },
    {
      title: "User Responsibilities",
      icon: UserIcon,
      content: [
        {
          subtitle: "Account Security",
          text: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use."
        },
        {
          subtitle: "Accurate Information",
          text: "You agree to provide accurate, current, and complete information when creating your account and using our services. You must update this information promptly if it changes."
        },
        {
          subtitle: "Compliance",
          text: "You agree to use our services only for lawful purposes and in accordance with these terms. You are responsible for ensuring your use complies with applicable laws and regulations."
        },
        {
          subtitle: "Data Accuracy",
          text: "While our AI strives for accuracy, you are ultimately responsible for reviewing and verifying the accuracy of your financial data and reports generated by our platform."
        }
      ]
    },
    {
      title: "Payment and Billing",
      icon: DocumentTextIcon,
      content: [
        {
          subtitle: "Subscription Fees",
          text: "Our services are provided on a subscription basis. You agree to pay all fees associated with your chosen subscription plan in advance of each billing period."
        },
        {
          subtitle: "Billing Cycles",
          text: "Billing occurs monthly or annually based on your selected plan. Fees are non-refundable except as required by law or as specified in our refund policy."
        },
        {
          subtitle: "Price Changes",
          text: "We reserve the right to modify our pricing with 30 days' notice to existing customers. Price changes will not affect your current billing period."
        },
        {
          subtitle: "Payment Methods",
          text: "We accept major credit cards and other payment methods as specified on our platform. You must maintain valid payment information on file."
        }
      ]
    },
    {
      title: "Intellectual Property",
      icon: ShieldCheckIcon,
      content: [
        {
          subtitle: "VeriGrade IP",
          text: "All intellectual property rights in our platform, including software, algorithms, and content, remain our exclusive property. You may not copy, modify, or distribute our intellectual property without permission."
        },
        {
          subtitle: "User Data",
          text: "You retain ownership of your data. By using our services, you grant us a limited license to use your data to provide and improve our services."
        },
        {
          subtitle: "Feedback",
          text: "Any feedback, suggestions, or ideas you provide about our services may be used by us without compensation or attribution."
        }
      ]
    },
    {
      title: "Limitation of Liability",
      icon: ExclamationTriangleIcon,
      content: [
        {
          subtitle: "Service Limitations",
          text: "Our services are provided 'as is' without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of our AI-generated results."
        },
        {
          subtitle: "Liability Cap",
          text: "Our total liability to you for any claims arising from these terms or our services shall not exceed the amount you paid us in the 12 months preceding the claim."
        },
        {
          subtitle: "Indirect Damages",
          text: "We shall not be liable for any indirect, incidental, special, or consequential damages, including but not limited to loss of profits, data, or business opportunities."
        }
      ]
    }
  ];

  return (
    <div className="bg-white">
      {/* Hero Section */}
      <section className="pt-24 pb-16 bg-gradient-to-br from-indigo-50 via-white to-blue-50">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
              Terms of
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-blue-600"> Service</span>
            </h1>
            <p className="mt-6 text-lg leading-8 text-gray-600 max-w-3xl mx-auto">
              These terms govern your use of VeriGrade's AI-powered bookkeeping platform and services.
            </p>
            <div className="mt-8 flex items-center justify-center gap-4 text-sm text-gray-500">
              <span>Last updated: January 15, 2024</span>
              <span>•</span>
              <span>Effective date: January 15, 2024</span>
            </div>
          </div>
        </div>
      </section>

      {/* Introduction */}
      <section className="py-16 bg-white">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="prose prose-lg max-w-none">
            <p className="text-lg text-gray-600 mb-8">
              Welcome to VeriGrade. These Terms of Service ("Terms") constitute a legally binding agreement between you and VeriGrade, Inc. ("VeriGrade," "we," "us," or "our") regarding your use of our AI-powered bookkeeping platform and related services.
            </p>
            <p className="text-lg text-gray-600">
              Please read these Terms carefully before using our services. By accessing or using our platform, you agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use our services.
            </p>
          </div>
        </div>
      </section>

      {/* Terms Sections */}
      <section className="py-24 bg-gray-50">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="space-y-16">
            {sections.map((section, sectionIndex) => (
              <div key={sectionIndex} className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8">
                <div className="flex items-center gap-4 mb-8">
                  <div className="flex items-center justify-center w-12 h-12 bg-indigo-100 rounded-lg">
                    <section.icon className="h-6 w-6 text-indigo-600" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-900">{section.title}</h2>
                </div>
                
                <div className="space-y-6">
                  {section.content.map((item, itemIndex) => (
                    <div key={itemIndex}>
                      <h3 className="text-lg font-semibold text-gray-900 mb-3">{item.subtitle}</h3>
                      <p className="text-gray-600 leading-relaxed">{item.text}</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Additional Terms */}
      <section className="py-24 bg-white">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="space-y-8">
            <div className="bg-gray-50 rounded-2xl p-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-6">Additional Terms</h2>
              
              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-3">Termination</h3>
                  <p className="text-gray-600">
                    Either party may terminate this agreement at any time. Upon termination, your access to our services will cease, and we will provide you with a copy of your data upon request, subject to our data retention policies.
                  </p>
                </div>
                
                <div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-3">Governing Law</h3>
                  <p className="text-gray-600">
                    These Terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law principles. Any disputes shall be resolved in the courts of San Francisco County, California.
                  </p>
                </div>
                
                <div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-3">Severability</h3>
                  <p className="text-gray-600">
                    If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions will remain in full force and effect.
                  </p>
                </div>
                
                <div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-3">Entire Agreement</h3>
                  <p className="text-gray-600">
                    These Terms, together with our Privacy Policy, constitute the entire agreement between you and VeriGrade regarding your use of our services and supersede all prior agreements and understandings.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact Information */}
      <section className="py-16 bg-gray-50">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8 text-center">
            <ScaleIcon className="h-12 w-12 text-indigo-600 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Questions About These Terms?</h2>
            <p className="text-gray-600 mb-6">
              If you have any questions about these Terms of Service, please contact our legal team.
            </p>
            <div className="space-y-2 text-gray-600">
              <p>Email: legal@verigrade.com</p>
              <p>Phone: 1-800-VERIGRADE</p>
              <p>Address: 123 Innovation Drive, San Francisco, CA 94105</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
