apiVersion: apps/v1
kind: Deployment
metadata:
  name: verigrade-backend
  labels:
    app: verigrade-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: verigrade-backend
  template:
    metadata:
      labels:
        app: verigrade-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-org/verigrade-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: jwt-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: redis-url
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: aws-secret-access-key
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: s3-bucket
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: openai-api-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: stripe-secret-key
        - name: PLAID_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: plaid-client-id
        - name: PLAID_SECRET
          valueFrom:
            secretKeyRef:
              name: verigrade-secrets
              key: plaid-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: verigrade-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: verigrade-backend-service
spec:
  selector:
    app: verigrade-backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verigrade-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: verigrade-secrets
type: Opaque
data:
  database-url: <base64-encoded-database-url>
  jwt-secret: <base64-encoded-jwt-secret>
  redis-url: <base64-encoded-redis-url>
  aws-access-key-id: <base64-encoded-aws-access-key-id>
  aws-secret-access-key: <base64-encoded-aws-secret-access-key>
  s3-bucket: <base64-encoded-s3-bucket>
  openai-api-key: <base64-encoded-openai-api-key>
  stripe-secret-key: <base64-encoded-stripe-secret-key>
  plaid-client-id: <base64-encoded-plaid-client-id>
  plaid-secret: <base64-encoded-plaid-secret>


